version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
  
  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"